product_dict = {
    "001": {
        "product_title": "Elf Bar",
        "product_description_short": "Disposable 20ml",
        "product_description_long": "Elf Bar 600 Disposable Vape Pod Device is a pre-filled nicotine salt disposable vape, featuring a draw-activated firing mechanism, 550mAh battery, and 2mL of 2% nicotine salt e-liquid. The Elf Bar 600 Disposable Vape Pod Device is small, compact, and lightweight, featuring a non-refillable and non-rechargeable design, ideal for travel or those on-the-go. The Elf Bar 600 Disposable Vape Pod Device is draw-activated and is devoid of any buttons, keeping the device clean and free of any clutter. The Elf Bar 600 Disposable Vape Pod Device is pre-filled with 2mL of 2% nicotine salt e-liquid and comes in a variety of flavors.",
        "product_price": 99,
        "product_discount_price": None,
        "product_flavor": "Cream Tobacco",
        "product_image": "product-data/product-images/elf-bar-engangs-vape-20mg-cream-tobacco.webp",
        "product_category": "Disposables",
        "product_subcategory": "Disposables single unit",
        "product_tags": ["tag1", "tag2", "tag3"],
        "product_ranking": 1,
        "product_stock": 10
    },
    "002": {
        "product_title": "Elf Bar",
        "product_description_short": "Disposable 20ml",
        "product_description_long": "Elf Bar 600 Disposable Vape Pod Device is a pre-filled nicotine salt disposable vape, featuring a draw-activated firing mechanism, 550mAh battery, and 2mL of 2% nicotine salt e-liquid. The Elf Bar 600 Disposable Vape Pod Device is small, compact, and lightweight, featuring a non-refillable and non-rechargeable design, ideal for travel or those on-the-go. The Elf Bar 600 Disposable Vape Pod Device is draw-activated and is devoid of any buttons, keeping the device clean and free of any clutter. The Elf Bar 600 Disposable Vape Pod Device is pre-filled with 2mL of 2% nicotine salt e-liquid and comes in a variety of flavors.",
        "product_price": 99,
        "product_discount_price": 79,
        "product_flavor": "Strawberry Kiwi",
        "product_image": "product-data/product-images/elf-bar-engangs-vape-20mg-strawberry-kiwi.webp",
        "product_category": "Disposables",
        "product_subcategory": "Disposables single unit",
        "product_tags": ["tag1", "tag2", "tag3"],
        "product_ranking": 2,
        "product_stock": 10
    },
    "003": {
        "product_title": "Elf Bar",
        "product_description_short": "Disposable 20ml",
        "product_description_long": "Elf Bar 600 Disposable Vape Pod Device is a pre-filled nicotine salt disposable vape, featuring a draw-activated firing mechanism, 550mAh battery, and 2mL of 2% nicotine salt e-liquid. The Elf Bar 600 Disposable Vape Pod Device is small, compact, and lightweight, featuring a non-refillable and non-rechargeable design, ideal for travel or those on-the-go. The Elf Bar 600 Disposable Vape Pod Device is draw-activated and is devoid of any buttons, keeping the device clean and free of any clutter. The Elf Bar 600 Disposable Vape Pod Device is pre-filled with 2mL of 2% nicotine salt e-liquid and comes in a variety of flavors.",
        "product_price": 99,
        "product_discount_price": None,
        "product_flavor": "Strawberry Ice",
        "product_image": "product-data/product-images/elf-bar-engangs-vape-20mg-strawberry-ice.webp",
        "product_category": "Disposables",
        "product_subcategory": "Disposables single unit",
        "product_tags": ["tag1", "tag2", "tag3"],
        "product_ranking": 10,
        "product_stock": 10
    },
    "004": {
        "product_title": "Elf Bar",
        "product_description_short": "Disposable 20ml",
        "product_description_long": "Elf Bar 600 Disposable Vape Pod Device is a pre-filled nicotine salt disposable vape, featuring a draw-activated firing mechanism, 550mAh battery, and 2mL of 2% nicotine salt e-liquid. The Elf Bar 600 Disposable Vape Pod Device is small, compact, and lightweight, featuring a non-refillable and non-rechargeable design, ideal for travel or those on-the-go. The Elf Bar 600 Disposable Vape Pod Device is draw-activated and is devoid of any buttons, keeping the device clean and free of any clutter. The Elf Bar 600 Disposable Vape Pod Device is pre-filled with 2mL of 2% nicotine salt e-liquid and comes in a variety of flavors.",
        "product_price": 99,
        "product_discount_price": None,
        "product_flavor": "Strawberry Ice Cream",
        "product_image": "product-data/product-images/elf-bar-engangs-vape-20mg-strawberry-ice-cream.webp",
        "product_category": "Disposables",
        "product_subcategory": "Disposables single unit",
        "product_tags": ["tag1", "tag2", "tag3"],
        "product_ranking": 10,
        "product_stock": 10
    },
    "008": {
        "product_title": "Elf Bar",
        "product_description_short": "Disposable 20ml",
        "product_description_long": "Elf Bar 600 Disposable Vape Pod Device is a pre-filled nicotine salt disposable vape, featuring a draw-activated firing mechanism, 550mAh battery, and 2mL of 2% nicotine salt e-liquid. The Elf Bar 600 Disposable Vape Pod Device is small, compact, and lightweight, featuring a non-refillable and non-rechargeable design, ideal for travel or those on-the-go. The Elf Bar 600 Disposable Vape Pod Device is draw-activated and is devoid of any buttons, keeping the device clean and free of any clutter. The Elf Bar 600 Disposable Vape Pod Device is pre-filled with 2mL of 2% nicotine salt e-liquid and comes in a variety of flavors.",
        "product_price": 99,
        "product_discount_price": 79,
        "product_flavor": "Spearmint",
        "product_image": "product-data/product-images/elf-bar-engangs-vape-20mg-spearmint.webp",
        "product_category": "Disposables",
        "product_subcategory": "Disposables single unit",
        "product_tags": ["tag1", "tag2", "tag3"],
        "product_ranking": 5,
        "product_stock": 10
    },
    "005": {
        "product_title": "Elf Bar",
        "product_description_short": "Disposable 20ml",
        "product_description_long": "Elf Bar 600 Disposable Vape Pod Device is a pre-filled nicotine salt disposable vape, featuring a draw-activated firing mechanism, 550mAh battery, and 2mL of 2% nicotine salt e-liquid. The Elf Bar 600 Disposable Vape Pod Device is small, compact, and lightweight, featuring a non-refillable and non-rechargeable design, ideal for travel or those on-the-go. The Elf Bar 600 Disposable Vape Pod Device is draw-activated and is devoid of any buttons, keeping the device clean and free of any clutter. The Elf Bar 600 Disposable Vape Pod Device is pre-filled with 2mL of 2% nicotine salt e-liquid and comes in a variety of flavors.",
        "product_price": 99,
        "product_discount_price": None,
        "product_flavor": "Mango",
        "product_image": "product-data/product-images/elf-bar-engangs-vape-20mg-mango.webp",
        "product_category": "Disposables",
        "product_subcategory": "Disposables single unit",
        "product_tags": ["tag1", "tag2", "tag3"],
        "product_ranking": 6,
        "product_stock": 10
    },
    "006": {
        "product_title": "Elf Bar",
        "product_description_short": "Disposable 20ml",
        "product_description_long": "Elf Bar 600 Disposable Vape Pod Device is a pre-filled nicotine salt disposable vape, featuring a draw-activated firing mechanism, 550mAh battery, and 2mL of 2% nicotine salt e-liquid. The Elf Bar 600 Disposable Vape Pod Device is small, compact, and lightweight, featuring a non-refillable and non-rechargeable design, ideal for travel or those on-the-go. The Elf Bar 600 Disposable Vape Pod Device is draw-activated and is devoid of any buttons, keeping the device clean and free of any clutter. The Elf Bar 600 Disposable Vape Pod Device is pre-filled with 2mL of 2% nicotine salt e-liquid and comes in a variety of flavors.",
        "product_price": 99,
        "product_discount_price": None,
        "product_flavor": "Grape",
        "product_image": "product-data/product-images/elf-bar-engangs-vape-20mg-grape.webp",
        "product_category": "Disposables",
        "product_subcategory": "Disposables single unit",
        "product_tags": ["tag1", "tag2", "tag3"],
        "product_ranking": 4,
        "product_stock": 10
    },
    "007": {
        "product_title": "Elf Bar",
        "product_description_short": "Disposable 20ml",
        "product_description_long": "Elf Bar 600 Disposable Vape Pod Device is a pre-filled nicotine salt disposable vape, featuring a draw-activated firing mechanism, 550mAh battery, and 2mL of 2% nicotine salt e-liquid. The Elf Bar 600 Disposable Vape Pod Device is small, compact, and lightweight, featuring a non-refillable and non-rechargeable design, ideal for travel or those on-the-go. The Elf Bar 600 Disposable Vape Pod Device is draw-activated and is devoid of any buttons, keeping the device clean and free of any clutter. The Elf Bar 600 Disposable Vape Pod Device is pre-filled with 2mL of 2% nicotine salt e-liquid and comes in a variety of flavors.",
        "product_price": 99,
        "product_discount_price": None,
        "product_flavor": "Elfbull ice",
        "product_image": "product-data/product-images/elf-bar-engangs-vape-20mg-elfbull-ice.webp",
        "product_category": "Disposables",
        "product_subcategory": "Disposables single unit",
        "product_tags": ["tag1", "tag2", "tag3"],
        "product_ranking": 4,
        "product_stock": 10
    },
    "009": {
        "product_title": "Elf Bar",
        "product_description_short": "Disposable 20ml",
        "product_description_long": "Elf Bar 600 Disposable Vape Pod Device is a pre-filled nicotine salt disposable vape, featuring a draw-activated firing mechanism, 550mAh battery, and 2mL of 2% nicotine salt e-liquid. The Elf Bar 600 Disposable Vape Pod Device is small, compact, and lightweight, featuring a non-refillable and non-rechargeable design, ideal for travel or those on-the-go. The Elf Bar 600 Disposable Vape Pod Device is draw-activated and is devoid of any buttons, keeping the device clean and free of any clutter. The Elf Bar 600 Disposable Vape Pod Device is pre-filled with 2mL of 2% nicotine salt e-liquid and comes in a variety of flavors.",
        "product_price": 99,
        "product_discount_price": None,
        "product_flavor": "Watermelon",
        "product_image": "product-data/product-images/elf-bar-engangs-vape-20mg-watermelon.webp",
        "product_category": "Disposables",
        "product_subcategory": "Disposables single unit",
        "product_tags": ["tag1", "tag2", "tag3"],
        "product_ranking": 6,
        "product_stock": 10
    },
}

