article_dict = {
    "001": {
        "type": "article",
        "box_header": "nyhet:",
        "main_title": """Den internationella succen kommer till Sverige – beställ din Elf
                Bar hos oss idag!""",
        "main_sub_header": """Elf Bar, den hyllade vaping-produkten som har tagit världen med storm, är äntligen tillgänglig i Sverige! Med enkelhet och smidighet har den erövrat vape-entusiasters hjärtan över hela världen. Och nu kan du också ta del av denna globala sensation genom att beställa din alldeles egna Elf Bar hos oss.""",
        "image_1": "blog/blog-images/elf-bar-blog.jpg",
        "image_alt_1": "Bild på kvinna som röker en elf bar engångs vape",
        "image_title_1": "Njut av smidigheten med din nya Elf Bar",
        "heading_1": "Smidig och enkel att använda",
        "paragraph_1": "Det som gör Elf Bar så älskad är dess tillgänglighet och bekvämlighet. Denna enhet är perfekt för alla som vill ha en enkel vaping-upplevelse utan krångel med coils och e-juice-fyllningar. Elf Bar levereras laddad och klar för användning. När den är slut behöver du bara kassera den och ta fram en ny. Enklare än så blir det inte!",
        "image_2": "blog/blog-images/elf-bar-blog-2.webp",
        "image_alt_2": "Bild på olika smakprofiler av Elf Bar",
        "image_title_2": "Några av Elf Bars alla smaker",
        "heading_2": "Mängder av smaker att välja på",
        "paragraph_2": "Med ett stort utbud av lockande smaker finns det något för alla smaklökar. Oavsett om du gillar fruktiga, svalkande eller krämiga smaker, har Elf Bar något som passar just dig. Utforska vårt sortiment och hitta din favorit!",
        "heading_3": "Beställ hos oss idag",
        "paragraph_3": "Att beställa din Elf Bar hos oss är enkelt. Besök vår hemsida och välj bland vårt utbud av Elf Bar-produkter. Med snabba leveransalternativ får du snart möjlighet att njuta av denna internationella vaping-sensation direkt i din hand.",
        "link_3": "../../engangsvapes.html",
        "link_3_text": "Kika på våra Elf Bar och andra engångsvapes här",
        "date": "10 aug, 2023",

    },
    "002": {
        "type": "article",
        "box_header": "forskning:",
        "main_title": """Minska Cigarettanvändning med E-cigaretter och Vapes: Hälsorisker och Fördelar""",
        "main_sub_header": """Att minska användningen av vanliga cigaretter kan vara fördelaktigt för folkhälsan, och e-cigaretter kan vara ett hjälpmedel för rökare som vill trappa ner sitt rökande. Men det är viktigt att vara medveten om att e-cigaretter också har sina egna hälsorisker, och dessa risker är under kontinuerlig forskning världen över.""",
        "image_1": "blog/blog-images/vape-healthy-blog.jpg",
        "image_alt_1": "Bild på glad man som håller i en engångsvape",
        "image_title_1": "Vape kan vara ett mindre skadligt alternativ till cigaretter",
        "heading_1": "Forskning om Hälsorisker vid E-cigaretthanvändning",
        "paragraph_1": "En nyligen genomförd studie vid Rutgers University i USA har undersökt hälsoriskerna med användning av e-cigaretter. Resultaten visade att ångan från e-cigaretter innehåller mycket lägre koncentrationer av cancerframkallande ämnen (aldehyder) jämfört med rök från vanliga cigaretter. Skillnaden var mellan 125 och 10 000 gånger lägre.",
        "heading_2": "Hälsorisker och PG-vätskor",
        "paragraph_2": "Forskarna undersökte skillnaderna mellan propylenglykol (PG) och vegetabiliskt glycerin (VG) i e-vätskor. Resultaten visade att vegetabiliskt glycerin börjar brytas ner och bilda potentiellt skadliga ämnen vid en högre temperatur än propylenglykol. Det innebär att e-cigaretter med högre PG-innehåll kan vara ett mindre riskabelt alternativ för rökare som vill minska hälsoriskerna.",
        "heading_3": "Diacetyl och \"Popcornlunga\" ",
        "paragraph_3": "Studien diskuterade även diacetyl, en smörarom, och dess koppling till \"popcornlunga\". Forskarna fann att användning av e-cigaretter inte innebar samma risk för denna sjukdom som tidigare trott. Även om diacetyl i vissa smaker kan bildas vid upphettning, var nivåerna mycket låga och långt under farliga gränser.",
        "heading_4": "Avslutande Ord",
        "paragraph_4": "Det är tydligt att e-cigaretter kan vara ett steg mot att minska rökvanor och potentiella hälsorisker, men de är inte helt riskfria. Som alltid är det klokt att hålla sig informerad genom pålitliga källor och vara medveten om hur man använder e-cigaretter på ett säkert sätt.",
        "link_4": "https://www.mdpi.com/1660-4601/17/16/5650/htm",
        "link_4_text": "Länk till forskningsrapporten",
        "date": "05 aug, 2023",
    },

    "003": {
        "type": "listicle",
        "box_header": "tips:",
        "main_title": "Våra 4 Favoritsmaker för Engångsvapes",
        "main_sub_header": "Världen av vape-smaker är som en resa genom smakens rike. Här är några utsökta smakprofiler som tar din vaping-upplevelse till en helt ny nivå:",
        "image_1": "blog/blog-images/watermelon-and-grape.jpg",
        "image_alt_1": "Bild på vattenmelon och vindruvor",
        "image_title_1": "Hitta din favoritsmak bland våra engångsvapes",
        "heading_1": "Creamy Tobacco",
        "paragraph_1": "En välblandad mix av tobak och krämiga undertoner skapar en unik smak, som ändå kommer att kännas bekant för dem som är vana vid tobaksrökning. Denna smak tar de traditionella tonerna av tobak och förser dem med en krämig twist som är perfekt för dem som letar efter något elegant och fylligt.",
        "heading_2": "Juicy Watermelon",
        "paragraph_2": " Precis som en svalkande vattenmelon på en solig dag erbjuder denna smak en fräsch och naturlig sötma. Den saftiga vattenmelonsmaken väcker bilder av sommardagar och ger en uppfriskande känsla som är svår att motstå.",
        "heading_3": "Apple",
        "paragraph_3": "För de som älskar sine shisha-smaker tar äppelsmaken dig till en traditionell atmosfär. Med en balanserad blandning av sött och kryddigt är denna smak en hyllning till den förtrollande smaken av äpple som man kan njuta av vid en shisha-session.",
        "heading_4": "Vindruva",
        "paragraph_4": "Denna fruktiga och saftiga druvsmak erbjuder en explosion av smak i varje drag. Som att tugga på en sval och saftig druvklase ger den en kombination av sötma och syrlighet som tillfredsställer dina smaklökar.",
        "paragraph_5": "Dessa vape-smaker öppnar dörren till en värld av kulinarisk njutning, var och en med sin egen unika karaktär. Oavsett om du längtar efter något krämigt och förföriskt, friskt och saftigt eller traditionellt och kryddigt, finns det en smakprofil som passar din personliga smakpreferens.",
        "link_5": "../../engangsvapes.html",
        "link_5_text": "Kika på våra engångsvapes och deras smaker här",
        "date": "03 aug, 2023",
    }
}